### ISSUE TITLE
When do you publish the BootUnlock?

### ISSUE THREAD

**Issue by BrunoFischerGermany** [openwall-com-au/BootUnlock#1]
Your Idea ist great, but when i can test your tool?

Greets

**Comment by galaxy4public** [comment]
Your wish is my command, @BrunoFischerGermany :)

Seriously, though: thanks for actually pinging me since I had it sitting for half an year in the uncommitted form - my perfectionism was taking the best of me.  Anyway, it is committed and is available now.  Have fun.
