### ISSUE TITLE
APFSUserAgent Prompt On Login

### ISSUE THREAD

**Issue by PeteClubSeven** [openwall-com-au/BootUnlock#22]
Hi,

I installed the latest version on my Mac mini running macOS 14.2. I enabled FileVault, created a second encrypted volume on my USB dock and went through the set up. Everything seemed fine but when I log into my original account (the account on the internal SSD) I get the following prompt: 
![image](https://github.com/openwall-com-au/BootUnlock/assets/130258664/b0c3977f-c904-4469-83bd-86c4ce9fbd31)

It happens every time, if I enter my login details the drive gets successfully mounted however if I click Deny then the normal decryption prompt shows: 
![image](https://github.com/openwall-com-au/BootUnlock/assets/130258664/ebf0bb73-0110-40e6-8a7e-d90bda5f3ab2)

Am I doing something wrong? I have Xcode installed.

**Comment by galaxy4public** [comment]
Could you please look into `/var/log/BootUnlock.log` and, perhaps, post in here?  It should help to understand what's going on.  I am running Sonoma 14.1 on M2 myself.  Will install 14.2.1 today and test it myself.

P.S. The screenshots you shared are from the normal behaviour of macOS (and should not be shown if BootUnlock did its job properly).

**Comment by PeteClubSeven** [comment]
I done some more testing and I think it was caused by me potentially copying over the user wrong or having my external SSD user set as a "Standard" account instead of an "Administrator". Sorry for the confusion, I have it working now.

**Comment by galaxy4public** [comment]
I have my user as "Standard" too.  Well, the installation of BootUnlock requires to be installed as an "Administrator", but it works before you login, so the "Standard" user should be fine.

**Comment by PeteClubSeven** [comment]
> I have my user as "Standard" too. Well, the installation of BootUnlock requires to be installed as an "Administrator", but it works before you login, so the "Standard" user should be fine.

I will play around again and see if I have the problem, if so I'll reopen the issue. I think I just made a mistake porting over my user profile :+1:

**Comment by PeteClubSeven** [comment]
Thanks a lot for making this btw, my cloud storage doesn't allow you to choose where files are downloaded and my 256GB Mac Mini is too small to store that stuff. Being able to have both drives encrypted is exactly what I wanted!
