### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by thuvh** [openwall-com-au/BootUnlock#23]
Is there any document to remove this tool?

**Comment by galaxy4public** [comment]
Not really, perhaps, I need to write one.  The tool is really tiny.  You will need to remove the `/Library/PrivilegedHelperTools/au.com.openwall.BootUnlock` folder and the `/Library/LaunchDaemons/au.com.openwall.BootUnlock.plist` file and this would completely remove the presence of BootUnlock from your system.  Also, there is a log in the `/var/log/BootUnlock.log` file, you may want to remove it too.

**Comment by thuvh** [comment]
thank you!
